[package]
name = "curl"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
url = "2.2"
structopt = "0.3"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
regex = "1.5"